import './global.css';

export const metadata = {
    title: 'Welcome to main-app',
    description: 'Generated by create-nx-workspace',
};

export const dynamic = "force-static";

export default function RootLayout({ children }: { children: React.ReactNode }) {

    return (
        <html lang="en" >
            <body>{children}</body>
        </html>
    );
}
